Acer2
cselab/korali pull request #522
Opened 2020-11-17 13:42 UTC by wadaniel

fixes in cacer, nn initialization without batch normalization, gaussian exploration for continuous action

2020-11-19 16:50 UTC, webepasc requested changes
Maybe to the small changes...

2020-11-19 16:50 UTC, webepasc commented on source/modules/neuralNetwork/layer/layer._cpp
> +    float xavierConstant = sqrt(6.0) / sqrt(_nodeCount + _prevLayer->_nodeCount + 2.0);
In the original paper (http://proceedings.mlr.press/v9/glorot10a/glorot10a.pdf) the +2 is not given, where do you have it from?

2020-11-19 16:50 UTC, webepasc commented on source/modules/neuralNetwork/layer/layer._cpp
> +        hyperparameters.push_back(xavierConstant * _nn->_xavierGenerator->getRandomNumber());
Didn't you want to make this an uniformGenerator for clarity?

2020-11-19 16:50 UTC, webepasc commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
Guidos trick for RL.. maybe make it configurable (it might not be the right thing for all problems)

2020-11-19 16:53 UTC, wadaniel commented on source/modules/neuralNetwork/layer/layer._cpp
> +    float xavierConstant = sqrt(6.0) / sqrt(_nodeCount + _prevLayer->_nodeCount + 2.0);
the number of params are the number of nodes plus a bias term, so in total 2 more (one for each layer)

2020-11-19 16:54 UTC, wadaniel commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
no idea where, ideas?

2020-11-19 16:56 UTC, webepasc commented on source/modules/neuralNetwork/layer/layer._cpp
> +    float xavierConstant = sqrt(6.0) / sqrt(_nodeCount + _prevLayer->_nodeCount + 2.0);
It said nothing about parameters. it is about the number of nodes in the layer...

2020-11-19 16:56 UTC, webepasc commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
In network.. scaleOutputWeigths ..?

2020-11-19 16:58 UTC, wadaniel commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
I find this ugly, the default would be 0.0 and then we had to bloat the korali apps

2020-11-19 17:00 UTC, wadaniel commented on source/modules/neuralNetwork/layer/layer._cpp
> +        hyperparameters.push_back(xavierConstant * _nn->_xavierGenerator->getRandomNumber());
will do

2020-11-19 17:00 UTC, wadaniel commented on source/modules/neuralNetwork/layer/layer._cpp
> +    float xavierConstant = sqrt(6.0) / sqrt(_nodeCount + _prevLayer->_nodeCount + 2.0);
right, its the number of nodes not parameter, I also found this: 

"We initialized the biases to be 0 and the weights Wij at
each layer with the following commonly used heuristic:"

I will fix the weight initialization

2020-11-19 17:11 UTC, webepasc commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
why, default would be 1.0 and in RL we make this trick specific. No hiding, no lying

2020-11-19 17:12 UTC, wadaniel commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
yes default would be 1.0, but I dont like the idea of applieing the factor in each app, but maybe tomorrow or Sergio has a better idea

2020-11-20 00:36 UTC, wadaniel commented on source/modules/neuralNetwork/layer/layer._cpp
> +    float xavierConstant = sqrt(6.0) / sqrt(_nodeCount + _prevLayer->_nodeCount + 2.0);
fixed

2020-11-20 00:36 UTC, wadaniel commented on source/modules/neuralNetwork/layer/layer._cpp
> +        hyperparameters.push_back(xavierConstant * _nn->_xavierGenerator->getRandomNumber());
fixed

2020-11-20 00:37 UTC, wadaniel commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
I wait for a suggestion from Sergio

2020-11-20 16:05 UTC, SergioMartin86 commented on source/modules/solver/agent/continuous/continuous._cpp
> +    // Clipping actions
so clipping should be removed in favor of truncated distributions

2020-11-23 08:25 UTC, wadaniel commented on source/modules/solver/agent/continuous/continuous._cpp
> +    // Clipping actions
not part of this pr

2020-11-23 09:40 UTC, wadaniel commented on source/modules/neuralNetwork/neuralNetwork._cpp
> +      for (size_t j = 0; j < layerParameters.size(); ++j) layerParameters[j] *= 0.1;
fixed as discussed in zoom

2020-11-23 10:41 UTC, SergioMartin86 approved these changes

2020-11-23 10:42 UTC, webepasc approved these changes

2020-11-23 10:43 UTC, merged