Dvracer
cselab/korali pull request #532
Opened 2020-12-11 12:22 UTC by wadaniel

2020-12-11 13:13 UTC, webepasc requested changes

2020-12-11 13:13 UTC, webepasc commented on source/modules/solver/agent/continuous/VRACER/VRACER._cpp
> +    std::vector<float> gradientLoss(1 + 2 * _problem->_actionVectorSize);
For god's sake, how was this even able to work

2020-12-11 13:13 UTC, webepasc commented on source/modules/solver/agent/discrete/dVRACER/dVRACER._cpp
> +knlohmann::json dVRACER::runPolicy(const std::vector<float> &state)
why are you outputting the mean and sd if you use the Q-based policy?

2020-12-14 10:15 UTC, webepasc approved these changes

2020-12-15 17:36 UTC, SergioMartin86 approved these changes

2020-12-15 18:27 UTC, merged