Mocma
cselab/korali pull request #540
Opened 2020-12-26 10:16 UTC by wadaniel

2020-12-28 19:48 UTC, SergioMartin86 requested changes
Please address the comment about making the MO problem more koralic.

2020-12-28 19:48 UTC, SergioMartin86 commented on source/modules/problem/multiobjectiveoptimization/multiobjectiveoptimization._hpp
> +class Multiobjectiveoptimization : public korali::Problem
This is not very Koralic. A better approach is
Problem/Optimization/SingleObjective
Problem/Optimization/MultiObjective
However, in this case extensive re-factoring on existing examples/study cases would be necessary to adjust to the new nomenclature.

An even better approach would be:

Have a vector of `objectives` in the existing `Problem/Optimization` where the default is 1 (single objective). Only MO-CMAES (for now) would support objectives.size() > 1.

2020-12-28 19:48 UTC, SergioMartin86 commented on source/modules/solver/solver.config
> +    "Name": [ "Variable Count" ],
New attribute for ALL solvers in korali, only used for MO-CMAES? Also never used as far as I've seen. Perhaps you forgot to remove it?

2020-12-30 13:52 UTC, wadaniel commented on source/modules/solver/solver.config
> +    "Name": [ "Variable Count" ],
I wish that every solver uses it sooner or later, 30% define a variable like "dimension" and the rest use the _k0->_variables.size() which I find too long in the code

we keep it and I start including it for some solvers?

2020-12-30 13:53 UTC, wadaniel commented on source/modules/problem/multiobjectiveoptimization/multiobjectiveoptimization._hpp
> +class Multiobjectiveoptimization : public korali::Problem
but a vector of objectives would imply n-times the model evaluations? I would like to keep the F(x) = [bla , blu]

2020-12-30 15:21 UTC, wadaniel commented on source/modules/solver/solver.config
> +    "Name": [ "Variable Count" ],
done

2020-12-30 15:22 UTC, wadaniel commented on source/modules/problem/multiobjectiveoptimization/multiobjectiveoptimization._hpp
> +class Multiobjectiveoptimization : public korali::Problem
removed mo problem, added evaluateMultiple, done

2020-12-31 11:36 UTC, SergioMartin86 approved these changes

2021-01-04 09:51 UTC, webepasc approved these changes

2021-01-04 10:01 UTC, merged