update compiler selection in install script
cselab/korali pull request #544
Opened 2021-01-12 17:20 UTC by gtarabat

2021-01-13 13:01 UTC, SergioMartin86 requested changes

2021-01-13 13:01 UTC, SergioMartin86 commented on install
> -  CUDNNLIBS+=" -lcudart -lcudnn -lcudnn_ops_infer -lcudnn_ops_train -lcudnn_cnn_infer -lcudnn_cnn_train -lcudnn_adv_infer -lcudnn_adv_train -Wl,-rpath -Wl,${CUDA_ROOT}/lib64/ -L${CUDA_ROOT}/lib64/ -W
Why this change? Removing this disables RNN support on CuDNN

2021-01-13 19:32 UTC, gtarabat reviewed
Fixed.

2021-01-13 19:34 UTC, gtarabat commented on install
> -  CUDNNLIBS+=" -lcudart -lcudnn -lcudnn_ops_infer -lcudnn_ops_train -lcudnn_cnn_infer -lcudnn_cnn_train -lcudnn_adv_infer -lcudnn_adv_train -Wl,-rpath -Wl,${CUDA_ROOT}/lib64/ -L${CUDA_ROOT}/lib64/ -W
It was a mistake. I fixed it.

2021-01-14 09:52 UTC, SergioMartin86 approved these changes

2021-01-14 11:17 UTC, wadaniel approved these changes

2021-01-14 11:27 UTC, merged