Cmairl
cselab/korali pull request #546
Opened 2021-01-13 13:45 UTC by wadaniel

moved irl example to study cases,
general work on irl,
minor fixes in lmcma and cmaes,
added testing frequency option for RL
added backup feature for RL
added new termination criteria for RL
printing action stdevs in vracer

2021-01-14 12:21 UTC, SergioMartin86 requested changes

2021-01-14 12:21 UTC, SergioMartin86 commented on source/modules/solver/agent/agent._cpp
> +void Agent::backupAgent()
It seems like you don't need this. Please take out

2021-01-14 12:21 UTC, SergioMartin86 commented on source/modules/solver/agent/agent._hpp
> +  void backupAgent();
Same here, please take out

2021-01-14 12:21 UTC, SergioMartin86 commented on source/modules/solver/agent/agent.config
> +    "Name": [ "Testing", "Backup Agent" ],
Same here, please take out

2021-01-14 12:21 UTC, SergioMartin86 commented on source/modules/solver/agent/continuous/VRACER/VRACER._cpp
> +        // Step towards old policy (gradient pointing to larger difference between old and current policy)
minor stylistic change: 
put comment above for loop, and have the for loop be a one-liner

2021-01-14 13:13 UTC, wadaniel commented on source/modules/solver/agent/agent.config
> +    "Name": [ "Testing", "Backup Agent" ],
thisone is needed

2021-01-14 13:13 UTC, wadaniel commented on source/modules/solver/agent/agent._hpp
> +  void backupAgent();
removed

2021-01-14 13:13 UTC, wadaniel commented on source/modules/solver/agent/agent._cpp
> +void Agent::backupAgent()
removed

2021-01-14 13:13 UTC, wadaniel commented on source/modules/solver/agent/continuous/VRACER/VRACER._cpp
> +        // Step towards old policy (gradient pointing to larger difference between old and current policy)
ok thx

2021-01-14 13:20 UTC, wadaniel commented on source/modules/solver/agent/agent.config
> +    "Name": [ "Testing", "Backup Agent" ],
in agent line 301, its a feature I am using now since it seems to improve convergence of cmairl, after testing I check if the testing reward improved, if not I reset to the best testing policy. also to note is that for testing I use a different environment, namely I compare the observed with generated actions. this feature seems to help to keep the agent on track and steering it as much as possible to the observed actions

2021-01-14 13:58 UTC, wadaniel commented on source/modules/solver/agent/agent.config
> +    "Name": [ "Testing", "Backup Agent" ],
removed

2021-01-14 16:12 UTC, SergioMartin86 requested changes

2021-01-14 16:12 UTC, SergioMartin86 commented on source/modules/solver/agent/agent.config
> +    "Description": "TODO."
oops, missed this in the first review. This needs filling :P

2021-01-14 18:52 UTC, wadaniel commented on source/modules/solver/agent/agent.config
> +    "Description": "TODO."
completed, I missed it too.

2021-01-15 08:11 UTC, SergioMartin86 approved these changes

2021-01-15 10:45 UTC, gtarabat approved these changes

2021-01-15 10:46 UTC, merged