L2regularizer
cselab/korali pull request #555
Opened 2021-02-04 12:51 UTC by wadaniel

added l2 regularization for NN weights update,
added DQN,
work on CMAIRL ,
minor cleanups,
fixed loading of RL runs,
includes some changes from gfpt-3 branch

2021-02-05 09:44 UTC, webepasc approved these changes

2021-02-05 09:44 UTC, webepasc commented on tools/rlview/__main__.py
> -  ax.fill_between(epList, (meanHistory-confIntervalHistory), (meanHistory+confIntervalHistory), color='b', alpha=.1, label='98% Confidence Interval (' + dirs[resId] + ')')
why no-more errorbars and rewards?

2021-02-05 09:47 UTC, wadaniel commented on tools/rlview/__main__.py
> -  ax.fill_between(epList, (meanHistory-confIntervalHistory), (meanHistory+confIntervalHistory), color='b', alpha=.1, label='98% Confidence Interval (' + dirs[resId] + ')')
changes in "sergios modules" are there because I updated my branch with his gfpt-3 branch

2021-02-05 09:52 UTC, webepasc commented on tools/rlview/__main__.py
> -  ax.fill_between(epList, (meanHistory-confIntervalHistory), (meanHistory+confIntervalHistory), color='b', alpha=.1, label='98% Confidence Interval (' + dirs[resId] + ')')
kk

2021-02-05 13:58 UTC, SergioMartin86 requested changes

2021-02-05 13:58 UTC, SergioMartin86 commented on source/modules/neuralNetwork/neuralNetwork._cpp
> -  // Allocating storage for formatted input gradients (only for training)
Please put it back, needed for ddpg

2021-02-05 13:58 UTC, SergioMartin86 commented on source/modules/neuralNetwork/neuralNetwork._hpp
> -   * @brief Formatted data for the NN input gradients. Format: NxIC (N: Mini-batch size, IC: Input channels).
put back for ddpg

2021-02-05 13:58 UTC, SergioMartin86 commented on source/modules/solver/agent/agent.config
> +   "Name": [ "L2 Regularization" ],
make more descriptive, either with 2 settings (on/off + magnitude) or say "L2 Regularization Importance"

2021-02-07 13:53 UTC, wadaniel commented on source/modules/solver/agent/agent.config
> +   "Name": [ "L2 Regularization" ],
done

2021-02-07 13:53 UTC, wadaniel commented on source/modules/neuralNetwork/neuralNetwork._hpp
> -   * @brief Formatted data for the NN input gradients. Format: NxIC (N: Mini-batch size, IC: Input channels).
done

2021-02-08 09:05 UTC, SergioMartin86 approved these changes

2021-02-08 09:06 UTC, webepasc approved these changes

2021-02-08 09:07 UTC, merged