Optimizations on RL + Optimizers
cselab/korali pull request #572
Opened 2021-04-26 09:46 UTC by SergioMartin86

- Several optimizations in performance of NN and continuous policy
- Re-added discrete vracer
- Added many optimizers

2021-04-26 13:58 UTC, webepasc requested changes

2021-04-26 13:58 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +      action[i] = curPolicy.distributionParameters[0];
shouln't this be curPolicy.distributionParameters[i];

2021-04-26 13:58 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +  importanceWeight = std::exp(logImportanceWeight);
for squashed normal we could also simply use the same as for the unbounded one, i.e. change if (_policyDistribution == "Unbounded Normal") to if (_policyDistribution == "Unbounded Normal" && _policyDistribution == "Squashed Normal") to avoid numerical difficulties

2021-04-26 13:58 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +  if (_policyDistribution == "Squashed Normal")
same applies here, to avoid numerical issues it should be equivalent to have if (_policyDistribution == "Unbounded Normal" && _policyDistribution == "Squashed Normal") for the importance weight part

2021-04-26 14:05 UTC, SergioMartin86 commented on source/modules/solver/agent/agent.config
> +    "Description": "The factor (f) by which te reward is scaled down. R = f * R"
Yes

2021-04-26 14:09 UTC, SergioMartin86 commented on examples/study.cases/openAIGym/_jobs/openAIGym_VRACER.sbatch
> +#SBATCH --output=/scratch/snx3000/smartin/logs/openAIGym_VRACER_%j.out
removed.

2021-04-26 14:10 UTC, SergioMartin86 commented on source/modules/solver/agent/continuous/continuous._cpp
> +      action[i] = curPolicy.distributionParameters[0];
yep, good that you spotted it

2021-04-27 13:47 UTC, wadaniel commented on source/modules/solver/learner/deepSupervisor/optimizers/fAdagrad.cpp
> +    _currentValue[i] = _currentValue[i] + (_eta / std::sqrt(_s[i] + _epsilon)) * gradient[i];
this update must come before the evaluation step, otherwise, _currentValue doesn't coincide with the evaluation (this needs to be fixed in all 'fast' solvers, I fixed it in the optimizer modules)

2021-04-27 13:47 UTC, wadaniel commented on source/modules/solver/agent/continuous/continuous._cpp
> +    if (_policyDistribution == "Unbounded Normal" || _policyDistribution == "Beta")
Id name it "Normal", not unbounded

2021-04-27 13:47 UTC, wadaniel commented on source/modules/solver/agent/continuous/continuous._cpp
> +  importanceWeight = std::exp(logImportanceWeight);
you mean || instead of &&

2021-04-27 13:47 UTC, wadaniel commented on source/modules/solver/agent/continuous/continuous._cpp
> +  if (_policyDistribution == "Squashed Normal")
why would it be equivalent? the imp weights are different, I don't see / remember the benefit of applying the same IW

2021-04-27 14:29 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +  importanceWeight = std::exp(logImportanceWeight);
Yes

2021-04-27 14:40 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +  if (_policyDistribution == "Squashed Normal")
From the definition of the density. It should also be evident from the subroutine squashedNormalLogDensity. Let me elaborate:

We compute importanceWeight = std::exp( logpCurPolicy - logpOldPolicy ), where 

logpOldPolicy += squashedNormalLogDensity(unboundedAction, oldMean, oldSigma, scale);
logpCurPolicy += squashedNormalLogDensity(unboundedAction, curMean, curSigma, scale);

and squashedNormalLogDensity returns

logExp - logConst - logStdDev -logDTanhX -logScale,

where

  // Compute contribution from normalLogDensity
  const T logExp = -std::pow((px - mean) / sigma, 2.0f) / 2.0f;
  static constexpr T logConst = 9.1893853320467266954096885456237942e-01f; // This is log(sqrt(2*pi))
  const T logStdDev = std::log(sigma);

  // Compute numerically safe factor from coordinate transformation
  const T tanhX = std::tanh(px);
  static constexpr T MIN = std::numeric_limits<T>::min();
  const T dTanhX = std::max(1.0f-tanhX*tanhX, MIN);
  const T logDTanhX = std::log(dTanhX);
  const T logScale = std::log(scale);

From this we see, that the only terms that depend on the mean and sigma are logExp and logStdDev, thus the others will cancel in the subtraction and the result is the same as for two Unbounded Normals evaluated at the unboundedAction.

2021-04-27 14:45 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +    if (_policyDistribution == "Unbounded Normal" || _policyDistribution == "Beta")
True, Unbounded Normal is a pleonasm :D

2021-04-27 14:46 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +  if (_policyDistribution == "Squashed Normal")
The same arguments also applies for the importance weight gradient

2021-04-27 15:02 UTC, webepasc commented on source/modules/solver/agent/continuous/continuous._cpp
> +  importanceWeight = std::exp(logImportanceWeight);
Yes

2021-04-27 16:13 UTC, SergioMartin86 commented on source/modules/solver/agent/continuous/continuous._cpp
> +    if (_policyDistribution == "Unbounded Normal" || _policyDistribution == "Beta")
You just wanted to use the word 'Pleonasm', right? :P 

Fixed.

2021-04-28 13:19 UTC, webepasc approved these changes

2021-04-28 13:32 UTC, webepasc approved these changes

2021-04-28 13:39 UTC, wadaniel approved these changes

2021-04-28 14:16 UTC, merged