openspiel tictactoe and leduc
cselab/korali pull request #605
Opened 2021-09-07 22:28 UTC by JonathanLehner

A demo with DQN for openspiel's tic tac toe and leduc poker for Korali, using only one NN to determine the moves of both players. We should probably use two NNs for practical purposes.

2021-09-08 06:50 UTC, webepasc requested changes

2021-09-08 06:50 UTC, webepasc commented on examples/features/checkpoint.resume/run-dvracer.py
> +sys.path.append('../../learning/reinforcement/openspiel_tic_tak_toe/_model')
This is not needed

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_leduc/_model/leduc.py
> +##  This code was inspired by the OpenAI Gym CartPole v0 environment
update header

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_leduc/_model/leduc.py
> +    if(cur_player < 0):
Am I getting it right that cur_player is -4 if game ended, or why is this check? Even if so, shouldn't there be no state read anymore after the termination is reached?

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_leduc/_model/leduc.py
> +      return 0 # no reward until game is over
You ideally want to avoid sparse reward, i.e. give a reward at every step

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_leduc/meson.build
> +e = find_program('run-vracer.py', required: true)
update this plain copy

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_tic_tak_toe/README.rst
> +Cartpole (Python)
update readme

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_leduc/README.rst
> +Cartpole (Python)
update readme

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_tic_tak_toe/_model/env.py
> +tictaktoe_game = TicTakToeGame()
Is there no way to unify the environments? Check /study.case/openAI for an example how this is done for the openAI benchmarks

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_tic_tak_toe/meson.build
> +e = find_program('run-vracer.py', required: true)
also here, do not just blindly copy stuff

2021-09-08 06:50 UTC, webepasc commented on examples/learning/reinforcement/openspiel_tic_tak_toe/run-dvracer.py
> +#!/usr/bin/env python3
To me it seems well feasible to make one folder with openSpiel, similar to openAI ..

2021-09-22 21:43 UTC, JonathanLehner commented on examples/learning/reinforcement/openspiel_leduc/_model/leduc.py
> +    if(cur_player < 0):
Yes, -4 in openspiel means game ended

2021-09-22 21:44 UTC, JonathanLehner commented on examples/learning/reinforcement/openspiel_leduc/_model/leduc.py
> +    if(cur_player < 0):
some algorithms can check the state after the game has ended, so I think it is better to check just in case

2021-09-22 21:49 UTC, JonathanLehner commented on examples/learning/reinforcement/openspiel_leduc/_model/leduc.py
> +      return 0 # no reward until game is over
How can we give a sparse reward in poker? The winner is only calculated after the game is over. Before this, we can punish illegal moves, but there is incomplete information about who will win, so it seems most approaches only give a reward in the end

2021-09-23 00:16 UTC, JonathanLehner commented on examples/learning/reinforcement/openspiel_leduc/meson.build
> +e = find_program('run-vracer.py', required: true)
this is for tests right? I should add more of them

2021-09-23 00:17 UTC, JonathanLehner commented on examples/learning/reinforcement/openspiel_tic_tak_toe/run-dvracer.py
> +#!/usr/bin/env python3
the openai folder is in study.cases. this is a bit confusing. What is the difference between examples and examples/study.cases? https://github.com/cselab/korali/tree/master/examples/study.cases/openAIGym

2021-09-24 11:58 UTC, JonathanLehner commented on examples/learning/reinforcement/openspiel_tic_tak_toe/meson.build
> +e = find_program('run-vracer.py', required: true)
yes i somehow missed this

2021-09-29 02:30 UTC, JonathanLehner commented
I updated the code. Turned based training of multiple agents is still outstanding

2021-10-04 12:49 UTC, webepasc reviewed
You are missing an install_deps.sh file that can be run in order to install all the external dependencies (i.e. in this case python3 -m pip install open_spiel)

2021-10-04 12:49 UTC, webepasc commented on examples/study.cases/openspiel/_model/env.py
> + if (envName == 'Humanoid-v2'):
this can go

2021-10-04 12:49 UTC, webepasc commented on examples/study.cases/openspiel/_model/env.py
> + if (envName == 'Ant-v2'):
this can go

2021-10-04 12:49 UTC, webepasc commented on examples/study.cases/openspiel/_model/oswrapper.py
> +##  This code is a wrapper for the Leduc Poker environment in Openspiel
typo: This code is a wrapper for the Leduc Poker environment in Openspiel -> This code is a wrapper for Openspiel

2021-10-04 12:49 UTC, webepasc commented on examples/study.cases/openspiel/_model/oswrapper.py
> +    state[0] = cur_player # Current player
what happens here?

2021-10-04 12:49 UTC, webepasc commented on examples/study.cases/openspiel/_model/env.py
> +  # Getting new action
I am missing the loop over all players here, how is the multi-agent aspect handled?

2021-10-05 09:07 UTC, webepasc commented on examples/study.cases/openspiel/_model/env.py
> +  # Performing the action
add note that player is automatically switching after advance

2021-10-12 17:06 UTC, JonathanLehner commented
@webepasc @wadaniel I added the changes. Is it ok now?

2021-10-15 10:12 UTC, JonathanLehner commented
RuntimeError:  + No value provided for mandatory setting: ['Training Reward Threshold'] required by reinforcementLearning for instance for /Users/jonathan/korali_files/korali/examples/learning/reinforcement/cartpole

2021-10-15 10:38 UTC, webepasc commented
Make sure you merged with the latest version of master, try to delete your build folder, and reinstall from scratch. The cartpole works without this setting. After reinstalling, make sure that you are not restarting from a previous run. 

Regarding your question: Select a game, for example Leduc Poker, and implement the performance metrics that are used in respective reference publication (for example the exploitability used in DREAM https://arxiv.org/pdf/2006.10410.pdf). We can discuss this in a meeting.

2022-08-08 14:03 UTC, closed without merging